"""users table

Revision ID: 4866ab894829
Revises: 2e1f9d63bf3d
Create Date: 2023-06-14 01:48:38.945423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4866ab894829'
down_revision = '2e1f9d63bf3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
