"""users table

Revision ID: 842e36dc0e8e
Revises: 4866ab894829
Create Date: 2023-06-14 01:50:57.967378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842e36dc0e8e'
down_revision = '4866ab894829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_login', table_name='User')
    op.drop_column('User', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('login', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_User_login', 'User', ['login'], unique=False)
    # ### end Alembic commands ###
