"""users table

Revision ID: f917aac2b112
Revises: 842e36dc0e8e
Create Date: 2023-06-14 01:51:55.381800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f917aac2b112'
down_revision = '842e36dc0e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('login', sa.String(length=64), nullable=True))
    op.drop_index('ix_User_username', table_name='User')
    op.create_index(op.f('ix_User_login'), 'User', ['login'], unique=True)
    op.drop_column('User', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_User_login'), table_name='User')
    op.create_index('ix_User_username', 'User', ['username'], unique=False)
    op.drop_column('User', 'login')
    # ### end Alembic commands ###
